# Generated by Django 3.0.7 on 2020-06-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20200618_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
